### ISSUE TITLE
最新内核全部构建失败

### ISSUE THREAD

**Issue by h88782481** [WeeAris/RK-KSU-AOSP-Daily-Build#1]
如题，内核更新后用github action全部构建失败

**Comment by h88782481** [comment]
开启CONFIG_SECCOMP之后可以就正常编译内核了

**Comment by WeeAris** [comment]
原来是你啊

**Comment by WeeAris** [comment]
> 开启CONFIG_SECCOMP之后可以就正常编译内核了

原来是你啊

**Comment by h88782481** [comment]
> > 开启CONFIG_SECCOMP之后可以就正常编译内核了
> 
> 原来是你啊

我说这个昵称咋这么眼熟，哈哈，大佬牛逼
